import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: "Baltai Energy - Transforming the Energy Landscape",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  bg-lightgrey text-darkgrey`}
      >
        {children}
      </body>
    </html>
  );
}
