"use client";
import { useEffect, useRef, useState } from "react";

import { AiOutlinePlus, AiOutlineMinus } from "react-icons/ai";

const accordionList = [
  {
    title: "Will solar power save me money?",
    content:
      "Yes, solar power will save you money. Solar energy is a long-term investment, and it works like prepaying your electricity costs all upfront and then reaping the benefits for years to come.",
  },
  {
    title: "Will Solar Power Get Cheaper?",
    content:
      " Solar power pricing has been on a steady decline for the last few years. However, most experts agree that the decreasing prices are on hold for now.",
  },
  {
    title: "Can Solar Power Be Stored?",
    content:
      "Solar power can be stored in batteries. This is done in systems that are grid-tied with battery backups and in off-grid solar systems.",
  },
  {
    title: "Can Solar Power My Whole House?",
    content:
      "Yes, one of the common misconceptions about solar power is that you run only certain items with the power that is produced. While this may be the case with off-grid systems, grid-tied systems do not provide power to specific devices. Instead, it simply provides a percentage of the electricity that your entire house uses.",
  },
  {
    title: "What are Solar Power Advantages?",
    content:
      "Solar power has grown massively in popularity in recent years, but it still has a long way to go before the majority of people are familiar with it. Some of the advantages of solar power are avoiding rising utility rates, tax benefits, helping the environment and independence.",
  },
  {
    title: "How do solar panels save money?",
    content:
      "Solar panels save money by reducing electricity costs, avoiding future price increases and potentially increasing property value.",
  },
  {
    title: "Can solar power my whole house?",
    content:
      "Yes, solar panels can power your entire house, and they can even produce excess energy that can be sold back to the grid. Factories and Cities can be powered with Solar Energy.",
  },
  {
    title: "How long do solar panels last?",
    content: "Solar panels can last for 25 years or more.",
  },
  {
    title: "Are solar panels worth it?",
    content:
      "Solar panels are worth it for many people due to their financial and environmental benefits. However, the cost of solar panels and their effectiveness vary by location and other factors.",
  },
  {
    title: "Can solar panels be recycled?",
    content:
      "Yes, retired solar panels can be recycled to reduce electronic waste and recover valuable materials.",
  },
  {
    title: "What are the different types of solar batteries?",
    content:
      "Solar batteries can be divided into six categories based on their chemical composition: Lithium-ion, lithium iron phosphate (LFP), lead-acid, flow, saltwater, and nickel-cadmium.",
  },
  {
    title: "How do solar batteries work?",
    content:
      "Solar batteries store electrical energy generated by photovoltaic panels. When solar panels generate more electricity than the electrical system demands, the excess is used to charge the batteries. Batteries transform the electrical energy they receive from photovoltaic modules into chemical energy.",
  },
  {
    title: "What is the lifespan of a solar battery?",
    content:
      "The useful life of a battery for solar installations is usually around ten years. However, their useful life plummets if frequent deep discharges (> 50%) are made. Therefore, it is advisable to install enough capacity so that 50% of the discharge is not exceeded.",
  },
  {
    title: "What type of battery is best for solar?",
    content: "Lithium-ion",
  },
  {
    title: "What is a solar inverter?",
    content:
      "Solar inverters convert DC power input and turn it into AC power. They also act as the primary connection between the panels and the electrical distribution panel in the house.",
  },
  {
    title: "How does a solar inverter work?",
    content:
      "A solar inverter is essential for your solar panel system to convert DC electricity into AC electricity for everyday use. The process begins with sunlight striking the photovoltaic cells of solar panels, creating a flow of DC electricity. However, since most homes and electrical grids use AC electricity, the DC electricity generated by solar panels needs to be converted. This is where the solar inverter steps in. Its main task is to convert the DC electricity into AC electricity with the appropriate voltage, frequency and phase, making it suitable for powering household appliances and feeding excess energy into the electrical grid.",
  },
];

const Accordion = () => {
  const [activeIndex, setActiveIndex] = useState(null);

  const handleActiveAccordion = (index) => {
    setActiveIndex((prev) => (prev === index ? null : index));
  };

  return accordionList.map((item, index) => (
    <AccordionItem
      key={index}
      index={index}
      title={item.title}
      content={item.content}
      isOpen={activeIndex === index}
      onClick={() => handleActiveAccordion(index)}
    />
  ));
};

export const AccordionItem = ({ index, title, content, isOpen, onClick }) => {
  const contentRef = useRef(null);

  useEffect(() => {
    if (contentRef.current) {
      contentRef.current.style.maxHeight = isOpen
        ? `${contentRef.current.scrollHeight}px`
        : "0px";
    }
  }, [isOpen]);

  return (
    <div className="">
      <div
        onClick={onClick}
        className="flex cursor-pointer font-medium items-center w-full gap-7 p-4 bg-white shadow-md relative transition duration-1000 ease-in-out"
      >
        <h1 className="after:content-[''] after:w-[1px] after:h-full after:bg-darkgrey after:opacity-70 after:absolute after:top-0 after:bottom-0 after:ml-[14px] md:text-lg lg:text-xl">
          {index + 1}
        </h1>

        <h1 className="w-full md:text-lg lg:text-xl">{title}</h1>

        <h1 className="flex justify-end">
          {isOpen ? (
            <AiOutlineMinus className="text-goldorange text-2xl" />
          ) : (
            <AiOutlinePlus className="text-goldorange text-2xl" />
          )}
        </h1>
      </div>

      <div className="">
        <p
          ref={contentRef}
          className={`text-sm my-2 overflow-hidden transition-max-height duration-300 md:text-base`}
        >
          {content}
        </p>
      </div>
    </div>
  );
};

export default Accordion;
